NorthwindUI/Models/CartlistViewModel.cs
using Entities.Concrete.DomainModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NorthwindUI.Models
{
    public class CartlistViewModel
    {
        public Cart Cart{ get; set; }
    }
}

NorthwindUI/Models/CategoryListViewModel.cs
using Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NorthwindUI.Models
{
    public class CategoryListViewModel
    {
        public List<Category> Categories { get; set; }
        public int CurrentCategory { get;  set; }
    }
}

NorthwindUI/Models/ErrorViewModel.cs
using System;

namespace NorthwindUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NorthwindUI/Models/ProductListViewModel.cs
using Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NorthwindUI.Models
{
    public class ProductListViewModel
    {
        public List<Product> Products{ get; set; }
    }
}

NorthwindUI/Models/ShippingDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NorthwindUI.Models
{
    public class ShippingDetail
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public string Adres { get; set; }
    }
}

NorthwindUI/Models/ShippingDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NorthwindUI.Models
{
    public class ShippingDetailsViewModel
    {
        public ShippingDetail ShippingDetail { get; set; }
    }
}

NorthwindUI/Controllers/CartController.cs
using Business.Abstract;
using Entities.Concrete;
using Entities.Concrete.DomainModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NorthwindUI.Helpers;
using NorthwindUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NorthwindUI.Controllers
{
    public class CartController : Controller
    {
        ICartSessionHelper _cartSessionHelper;
        ICartService _cartService;
        IProductService _productService;

        public CartController(ICartSessionHelper cartSessionHelper, ICartService cartService, IProductService productService)
        {
            _cartSessionHelper = cartSessionHelper;
            _cartService = cartService;
            _productService = productService;
        }

        public IActionResult Index()
        {
            var model = new CartlistViewModel()
            {
                Cart = _cartSessionHelper.GetCart("cart")
            };
            return View(model);
        }
        public IActionResult AddToCart(int id)
        {
            Product product = _productService.GetProductById(id);
            var cart = _cartSessionHelper.GetCart("cart");
            _cartService.AddToCart(cart, product);
            _cartSessionHelper.SetToCart("cart", cart);
            TempData.Add("Message", product.ProductName + " has been added to your cart!");
            return RedirectToAction("Index", "Product");
        }
        public IActionResult RemoveFromCart(int id)
        {
            Product product = _productService.GetProductById(id);
            var cart = _cartSessionHelper.GetCart("cart");
            _cartService.RemoveFromCart(cart,id);
            _cartSessionHelper.SetToCart("cart", cart);
            TempData.Add("Message", product.ProductName + " has been removed from your cart!");
            return RedirectToAction("Index");
        }

        public IActionResult Complete()
        {
            var model = new ShippingDetailsViewModel()
            {
                ShippingDetail = new ShippingDetail()
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Complete(ShippingDetail shippingDetail)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            TempData.Add("message", "Your order has been successfully completed.");
            _cartSessionHelper.RemoveCart("cart");
            return RedirectToAction("Index");
        }



    }
}

NorthwindUI/Controllers/CategoryController.cs
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using NorthwindUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NorthwindUI.Controllers
{
    public class CategoryController :Controller
    {
        ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

    
    }
}

NorthwindUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NorthwindUI.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace NorthwindUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
            
        }
    }
}

NorthwindUI/Controllers/ProductController.cs
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using NorthwindUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NorthwindUI.Controllers
{
    public class ProductController : Controller
    {
        IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult Index(int category)
        {
            var model = new ProductListViewModel()
            {
                Products = category > 0 ? _productService.GetProducts(category) : _productService.GetProducts(),
            };
            return View(model);
        }
    }
}

NorthwindUI/ViewComponents/CategoryListViewComponent.cs
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using NorthwindUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NorthwindUI.ViewComponents
{
    public class CategoryListViewComponent : ViewComponent //ViewComponent Inheritance
    {
        ICategoryService _categoryService;

        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public ViewViewComponentResult Invoke() // ViewComponent kullanımı için ViewViewComponentResult classını kullanmam ve ismine Invoke() vermem gerekli..
        {
            var model = new CategoryListViewModel()
            {
                Categories = _categoryService.GetCategories(),
                CurrentCategory = Convert.ToInt32(HttpContext.Request.Query["category"]) //QUERY STRING OKUMA <-------
            };
            return View(model);
        }
    }
}

NorthwindUI/Views/Cart/Complete.cshtml
@model ShippingDetailsViewModel

<form asp-controller="Cart" asp-action="Complete" method="post">
    <div class="row">
        <div class="form-group col-6">
            <label asp-for="@Model.ShippingDetail.FirstName">Name</label>
            <input asp-for="@Model.ShippingDetail.FirstName" class="form-control" placeholder="Name" />
            <span asp-validation-for="@Model.ShippingDetail.FirstName"></span>

        </div>
        <div class="form-group col-6">
            <label asp-for="@Model.ShippingDetail.LastName">Surname</label>
            <input asp-for="@Model.ShippingDetail.LastName" class="form-control" placeholder="Surname" />
            <span asp-validation-for="@Model.ShippingDetail.LastName"></span>
        </div>
    </div>

    <div class="row">
        <div class="form-group col-6">
            <label asp-for="@Model.ShippingDetail.Adres">Adress</label>
            <input asp-for="@Model.ShippingDetail.Adres" class="form-control" placeholder="Adress" />
            <span asp-validation-for="@Model.ShippingDetail.Adres"></span>
        </div>
        <div class="form-group col-6">
            <label asp-for="@Model.ShippingDetail.Age">Age</label>
            <input asp-for="@Model.ShippingDetail.Age" class="form-control" placeholder="Age" />
            <span asp-validation-for="@Model.ShippingDetail.Age"></span>
        </div>

    </div>

    <input class="btn btn-outline-dark" type="submit" value="Complete" />


</form>

NorthwindUI/Views/Cart/Index.cshtml
@model CartlistViewModel



<table class="table table-responsive">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Description</th>
            <th>Price</th>
            <th>Stock</th>
            <th>Quantity</th>

        </tr>
    </thead>
    <tbody>

        @if (Model.Cart.cartLines.Count == 0)
        {
            <tr class="text-center">
                <td colspan="6">No matching records found</td>
            </tr>
        }
        @foreach (var product in Model.Cart.cartLines)
        {
            <tr>
                <td>@product.Products.ProductID</td>
                <td>@product.Products.ProductName</td>
                <td>@product.Products.UnitPrice</td>
                <td>@product.Products.QuantityPerUnit</td>
                <td>@product.Products.UnitsInStock</td>
                <td>@product.Quantity</td>
                <td><a class="btn btn-sm btn-danger" asp-action="RemoveFromCart" asp-controller="Cart" asp-route-id="@product.Products.ProductID">Remove</a></td>
            </tr>
        }
    </tbody>
</table>
<a asp-action="Complete" asp-controller="Cart" class="btn btn-success">Buy</a>

NorthwindUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

NorthwindUI/Views/Product/Index.cshtml
@model ProductListViewModel

@{
    ViewData["Title"] = "MY PAGE";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<table class="table table-responsive">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>QuantityPerUnit</th>
            <th>UnitPrice</th>
            <th>UnitsInStock</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model.Products)
        {
            <tr>
                <td>@product.ProductID</td>
                <td>@product.ProductName</td>
                <td>@product.QuantityPerUnit</td>
                <td>@product.UnitPrice</td>
                <td>@product.UnitsInStock</td>
                <td><a class="btn btn-primary btn-sm" asp-action="AddToCart" asp-controller="Cart" asp-route-id="@product.ProductID">Add To Cart</a></td>
            </tr>
        }
    </tbody>
</table>

NorthwindUI/Views/Shared/Components/CategoryList/Default.cshtml
@model CategoryListViewModel



<div class="list-group">
    <a href="/product/index" class="list-group-item">All Products</a>
    @foreach (var category in Model.Categories)
    {
        var isActive = "list-group-item";
        if (category.CategoryID == Model.CurrentCategory)
        {
            isActive += " active";
        }
        <a href="/product/index?category=@category.CategoryID" class="@isActive">@category.CategoryName</a>
    }
</div>

NorthwindUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NorthwindUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Product" asp-action="Index">NorthwindUI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Your Cart</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="row">

                <div class="col-12">
                    @if (TempData["message"] != null)
                    {
                        <div class="alert alert-info">@TempData["message"]</div>
                    }

                </div>
            </div>
            <div class="row">

                <div class="col-3">
                    <!--CategoryList  :  MVC PartialView Mantığı, bu şekilde ViewComponent çağırıyoruz...-->
                    @await Component.InvokeAsync("CategoryList");
                </div>
                <div class="col-9">
                    <!--Products-->

                    @RenderBody()
                </div>

            </div>

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - NorthwindUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>